name: Deploy to Azure App Service
 
on:
  push:
    branches:
      - Emre-Pipline
 
permissions:
  id-token: write
  contents: read
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
 
 
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: DemoPipeline123
        package: .
